server:
  port: 8000
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XFl0Kt80CSouAOd3u0Q8kyjQMHuJb0izBE8pH/KJzzZyMZlNIJWCpwCBGNEoTkL25445VkNqXdBscRlM2hkluBlS8em0PrnC3BFWqCADXzOTUqZJlGCmjW7SbgxLiCDZ1yJBmSNVFQYwWZUAKnCh/ghbPcksQVVqglRPO+Uebrtzq5qwMYQ5g6omJhMeYcs4)
    username: ENC(27xTCeTSZsIf1cTtHXRLuM8yJeFCDiHW2T3uf3D3F/2JvBVDQptDP23jD+0bDBK+)
    password: qweqwe123!@# # 암호화 필요



  security:
    user:
      name: admin
      password: admin
  #    # OAuth 설정
  #    oauth2:
  #      client:
  #        registration:
  #          kakao:
  #            client-id: hex 추가
  #            client-secret: hex 추가
  #            redirect-uri: http://localhost:3000/login-callback/kakao
  #            client-authentication-method: POST
  #            authorization-grant-type: authorization_code
  #            client_name: kakao
  #          google:
  #            client-id: hex 추가.apps.googleusercontent.com
  #            client-secret: hex 추가
  #            redirect-uri: http://localhost:3000/login-callback/google
  #        provider:
  #          kakao:
  #            authorization-uri: https://kauth.kakao.com/oauth/authorize
  #            token-uri: https://kauth.kakao.com/oauth/token
  #            user-info-uri: https://kapi.kakao.com/v2/user/me
  #            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    open-in-view: false


jwt:
  token:
    secret-key: ENC(HFgq9BQv+A2rNULnmfkEvD1BXVAiUZQt58MniHjoyfqYjqbthDpR0bJ82Xb6tuJAAP6xtpUHCL+SM9W+U5jSE6EkOww2LotYyOC36qwPF5hZunKnEdzjorKuWDZmHM7nL0vi2rboU6KIZIjoYOh+cQ==)
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000
  redis:
    host: redis
    port: 6379
    password: rotto123 # 암호화 필요


# Multipart File Upload Setting
file:
  multipart:
    maxUploadSize: 1000000
    maxUploadSizePerFile: 1000000


# Swagger setting
springdoc:
  packages-to-scan: com.rezero.rotto.api.controller
  swagger-ui:
    path: /api-docs
    groups-order: DESC
    tags:sorter: alpha
    operations-sorter: alpha
    disabled-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  show-actuator: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


  # log level Setting
  logging:
    level:
      root: info
      org:
        springframework:
          root: debug
          web: debug
      com:
        rotto: debug
      zaxxer:
        hikari:
          pool:
            HikariPool: debug


# S3 Bucket
cloud:
  aws:
    s3:
      # 수정 필요
      bucket: rotto-rotto
    region:
      static: ENC(Lr5TujExoZ6kj+9RAOqLk17l/K7x3Wle6T8oHXJ1Cdbn4F2rennKK3R1WAjBgJSx)
    credentials:
      access-key: 추가
      secret-key: 추가
    stack:
      auto: false

